### ISSUE TITLE
[Egg Request]: DayZ Standalone (Stable Branch)

### ISSUE THREAD

**Issue by EpsilonCommunity** [pelican-eggs/eggs#1348] opened 2021-09-23 10:03 UTC
### Service

DayZ Standalone

### Does this expand an already existing service

No

### Link to game

dayz.com

### Links for server downloads

steam servers cmd

### Links for the install docs

https://community.bistudio.com/wiki/Category:DayZ:_Server

**Comment by EpsilonCommunity** [comment] 2021-09-23 10:03
Hi, here's a Linux Game Server Manager script, might be useful. :)

https://github.com/thelastnoc/dayz-sa_linuxserver

**Comment by gOOvER** [comment] 2021-09-23 10:36
DayZ Linux Server have atm a Bug. You cant run DayZ until its fixed, in a Docker Container, because Profile Flag dont Work.

I Allready created an Egg and i takeld with the Dev of the Linux Server. When Fix is Out i will Release it

**Comment by zigazajc007** [comment] 2021-11-30 08:55
Any updates?

**Comment by gOOvER** [comment] 2021-12-01 13:40
@zigazajc007 No. IT looks like, the Linux Server will not get Updates anymore

**Comment by zigazajc007** [comment] 2021-12-01 14:11
@gOOvER Don't worry. This would change as soon as Windows fall down. When Gaming would become easier on Linux.

**Comment by gOOvER** [comment] 2021-12-29 17:41
When this is fixed, a DayZ Server is possible; As i said; i have since first release an Egg, but it do notr really work.

See this Bug: https://github.com/pterodactyl/panel/issues/3830

**Comment by MistakingManx** [comment] 2022-04-08 07:19
Could you not just use a Windows image for the docker container?

**Comment by gOOvER** [comment] 2022-04-08 07:21
> Could you not just use a Windows image for the docker container?

DayZ Windows dont work in WIne

**Comment by MistakingManx** [comment] 2022-04-08 07:29
> > Could you not just use a Windows image for the docker container?
> 
> DayZ Windows dont work in WIne

I didn't mean to suggest Wine, when you load an "image" for a container, doesn't it basically act like a different operating system?

You could start with a windows image in that case, right?

**Comment by gOOvER** [comment] 2022-04-08 07:31
> > > Could you not just use a Windows image for the docker container?
> > 
> > 
> > DayZ Windows dont work in WIne
> 
> I didn't mean to suggest Wine, when you load an "image" for a container, doesn't it basically act like a different operating system?
> 
> You could start with a windows image in that case, right?

No, you cant use an Windows Image in Ptero

**Comment by MistakingManx** [comment] 2022-04-08 17:27
> > > > Could you not just use a Windows image for the docker container?
> > > 
> > > 
> > > DayZ Windows dont work in WIne
> > 
> > 
> > I didn't mean to suggest Wine, when you load an "image" for a container, doesn't it basically act like a different operating system?
> > You could start with a windows image in that case, right?
> 
> No, you cant use an Windows Image in Ptero

sadness.. why not?

**Comment by AlpacaServers** [comment] 2022-04-13 06:59
https://steamcommunity.com/sharedfiles/filedetails/?id=1517338673 is this anything?

**Comment by vojtechmares** [comment] 2022-05-24 19:56
> > > > > Could you not just use a Windows image for the docker container?
> > > > 
> > > > 
> > > > DayZ Windows dont work in WIne
> > > 
> > > 
> > > I didn't mean to suggest Wine, when you load an "image" for a container, doesn't it basically act like a different operating system?
> > > You could start with a windows image in that case, right?
> > 
> > 
> > No, you cant use an Windows Image in Ptero
> 
> sadness.. why not?

Hello, you can't run windows based docker images on linux, since containers are not virtualization, they are only kernel namespaces and cgroups (isolating the proces from the rest of OS and sharing the kernel of host os).

Since Windows does not have a linux kernel (and vice versa), you can't run a windows-based docker on linux (and vice versa).

**Comment by pixelapocalypseuk** [comment] 2022-06-11 16:39
Im not sure thats exactly true is it? I thought you can run linux containers on windows using wsl2 or windows containers but not both at the same time?
Could be wrong in that but it was my understanding?

Regards
XMortX

**Comment by Software-Noob** [comment] 2022-06-12 20:22
> Im not sure thats exactly true is it? I thought you can run linux containers on windows using wsl2 or windows containers but not both at the same time? Could be wrong in that but it was my understanding?
> 
> Regards XMortX

You can only run Windows containers on a Windows system. The containers share the host OS kernel drivers and resources. Pterodactyl doesn't support Windows environments, so WSL2 or LCOW is not considered.

**Comment by pixelapocalypseuk** [comment] 2022-06-12 20:25
Hey, sorry reading that back it may have seemed a bit confrontational, it was intended as a genuine question. 
But yeah i just wanted to make sure i was misunderstanding docker more than anything!

Regards
XMortX

**Comment by Hosting101** [comment] 2023-02-23 19:19
Hey guys, any news about dayz standalone egg?

**Comment by lilkingjr1** [comment] 2023-02-23 22:59
> Hey guys, any news about dayz standalone egg?

Please see the existing DayZ egg README in this repo for a (still valid) explanation.

**Comment by norbee16** [comment] 2024-04-28 23:46
Added server files 20.02.2024, https://forums.dayz.com/topic/259072-stable-update-124/
https://community.bistudio.com/wiki/DayZ:Hosting_a_Linux_Server

**Comment by lilkingjr1** [comment] 2024-04-29 02:50
Moving to more updated issue #2749

**Closed by lilkingjr1** 2024-04-29 02:50 UTC
Labels: egg request, progress stopped, not-feasable

**Comment by Mehdi-ExAo** [comment] 2024-05-09 12:27
Any updates?

**Comment by gOOvER** [comment] 2024-05-09 12:30
> Any updates?

![msedge_KyRgCXHU1u](https://github.com/pelican-eggs/eggs/assets/116325/085b5e52-d8a8-4584-a0e0-ad60a662bbc5)

**Comment by lilkingjr1** [comment] 2024-05-09 19:30
@Mehdi-ExAo More accurately, it's discussion has been moved.
